# Generated by Django 4.2 on 2023-04-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0005_alter_users_email_alter_users_img_alter_users_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='img',
            field=models.ImageField(upload_to='static/assets/img'),
        ),
    ]
