# Generated by Django 4.2 on 2023-04-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0006_alter_users_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.CharField(max_length=14),
        ),
    ]
